# Generated by Django 3.1.5 on 2021-01-09 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseselection', '0017_major_supported'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='term_code',
            field=models.CharField(db_index=True, default=1202, max_length=4, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_schedule',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_state',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
